/*
 * generated by Xtext 2.21.0
 */
package io.mdsl.validation;


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class APIDescriptionValidator extends AbstractAPIDescriptionValidator {
		
}
