/*
 * generated by Xtext 2.20.0
 */
package io.mdsl.validation;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.EValidatorRegistrar;

import io.mdsl.apiDescription.ApiDescriptionPackage;
import io.mdsl.apiDescription.DataContract;
import io.mdsl.apiDescription.GenericParameter;
import io.mdsl.apiDescription.ParameterForest;
import io.mdsl.apiDescription.ParameterTree;
import io.mdsl.apiDescription.RoleAndType;
/**
 * This class contains custom validation rules.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class DataTypeValidator extends AbstractMDSLValidator {
	
	public final static String LOWER_CASE_NAME = "LOWER_CASE_NAME";
	public final static String TYPE_MISSING = "TYPE_MISSING";
	public final static String TYPE_INCOMPLETE = "TYPE_INCOMPLETE";
	
	@Override
	public void register(EValidatorRegistrar registrar) {
		// not needed for classes used as ComposedCheck
	}

	@Check
	public void checkRoleAndType(final RoleAndType rat) {
		String role = rat.getRole();
		String basicType = rat.getBtype();
		
		if(basicType==null || basicType.equals("")) {
			info("Incomplete specification: No type such as <string> or <int> specified yet.", rat, ApiDescriptionPackage.eINSTANCE.getRoleAndType_Btype(), TYPE_INCOMPLETE); // ()Literals.ROLE_AND_TYPE__BTYPE);
	    }
		else if(basicType.equals("void")) {
			info("Imprecise specification: <void> only makes sense as sole element of a response message; you might want to remove the empty message from the specification.", rat, ApiDescriptionPackage.eINSTANCE.getRoleAndType_Btype()); // Literals.ROLE_AND_TYPE__BTYPE);
	    }
		else if(role.equals("ID") && !(basicType.equals("int")|| basicType.equals("string"))) {
			warning("The role-type combination ID<" + basicType + "> is somewhat unusual. Use ID<string> or ID<int> instead?", rat, ApiDescriptionPackage.eINSTANCE.getRoleAndType_Btype()); // Literals.ROLE_AND_TYPE__BTYPE);
	    }
		else if(role.equals("L") && !(basicType.equals("int") || basicType.equals("string"))) {
			warning("The role-type combination L<" + basicType + "> is somewhat unusual. Use L<string> or L<int> instead?", rat, ApiDescriptionPackage.eINSTANCE.getRoleAndType_Btype()); // Literals.ROLE_AND_TYPE__BTYPE);
	    }
		else if(role.equals("MD") && basicType.equals("raw")) {
			warning("The role-type combination MD<raw> is somewhat unusual. Use MD<string> instead?", rat, ApiDescriptionPackage.eINSTANCE.getRoleAndType_Btype()); // Literals.ROLE_AND_TYPE__BTYPE);
	    }
	}

	@Check
	public void checkIncompleteTypeInformation(final GenericParameter gp) {
		if(gp.getName() != null) {
			warning("\"" + gp.getName() + "\" is a generic parameter. You might want to provide a full identfier-role-type triple before invoking any generator.", gp, ApiDescriptionPackage.eINSTANCE.getGenericParameter_P(), TYPE_MISSING); // Literals.GENERIC_PARAMETER__P);
		}
		else {
			warning("This is a generic parameter. You might want to provide a full identfier-role-type triple. See MDSL documentation at https://microservice-api-patterns.github.io/MDSL-Specification/datacontract.", gp, ApiDescriptionPackage.eINSTANCE.getGenericParameter_P(), TYPE_MISSING); // Literals.GENERIC_PARAMETER__P);
		}
	}
	
	@Check
	public void checkInappropriateTypeName(final DataContract dc) {
        if (!Character.isUpperCase(dc.getName().charAt(0))) {
            warning("Data type name should start with a capital", dc, ApiDescriptionPackage.eINSTANCE.getDataContract_Name(), LOWER_CASE_NAME);
        }
	}

	@Check
	public void checkParameterForestAsTuple(final ParameterForest pf) {
		List<ParameterTree> trees = new ArrayList<ParameterTree>();
		trees.add(pf.getPtl().getFirst());
		trees.addAll(pf.getPtl().getNext());

		for (ParameterTree pt : trees) {
			if (pt.getName() != null) {
				// parameterForest is considered like a tuple
				info("ParameterForest are like tuples. Tuple items names are ignored.",
						pt, ApiDescriptionPackage.eINSTANCE.getParameterTree_Name()); //  Literals.PARAMETER_TREE__NAME);
			}
		}

	}
}