/*
 * generated by Xtext 2.20.0
 */
package io.mdsl.validation;

import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.EValidatorRegistrar;

import io.mdsl.apiDescription.ApiDescriptionPackage;
import io.mdsl.apiDescription.endpointContract;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class EndpointContractValidator extends AbstractAPIDescriptionValidator {

	@Override
	public void register(EValidatorRegistrar registrar) {
		// not needed for classes used as ComposedCheck
	}
	
	@Check
	public void reportContractSize(endpointContract epc) {
		int opsInContract = epc.getOps().size();
		String code = "API Metric"; // does not seem to be used? 
		info(epc.getName() + " exposes " + opsInContract + " operation(s)", epc, ApiDescriptionPackage.Literals.ENDPOINT_CONTRACT__NAME, code,  code);
	}
}
