openapi: 3.0.1
info:
  title: TestAPI
  version: "1.0"
servers: []
tags:
- name: TestEndpoint
  externalDocs:
    description: TestEndpoint contract, Information Holder Resource role
    url: https://microservice-api-patterns.org/patterns/responsibility/endpointRoles/InformationHolderResource.html
paths:
  /TestEndpoint:
    summary: general data-oriented endpoint
    post:
      tags:
      - TestEndpoint
      summary: createTest (Creates new Test object method)
      description: Creates new Test object
      operationId: createTest
      requestBody:
        description: Message payload (content)
        content:
          application/json:
            schema:
              type: object
              properties:
                attr1:
                  type: string
                  description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
                    target="_blank">Data Element</a>
              description: request body elements for createTest
      responses:
        "200":
          description: no return value
          content: {}
components:
  schemas: {}
