/*
 * generated by Xtext 2.20.0
 */
package io.mdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class APIDescriptionUiModule extends AbstractAPIDescriptionUiModule {

	public APIDescriptionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
