package io.mdsl.exception;

public class MDSLException extends RuntimeException {

	/**
	 * default id, generated by quick fix
	 */
	private static final long serialVersionUID = 1L;
	private String reason;

	public MDSLException(String reason) {
		super(reason);
		this.reason = reason;
	}

	public MDSLException(String reason, Exception e) {
		super(reason, e);
		this.reason = reason;
	}

	public String getReason() {
		return reason;
	}
}
