/*
 * generated by Xtext 2.35.0
 */
package io.mdsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class APIDescriptionRuntimeModule extends AbstractAPIDescriptionRuntimeModule {
}
